/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package murcia.fernando.proyectoJDBC.factory;

import java.sql.Connection;
import murcia.fernando.proyectoJDBC.dao.*;
import murcia.fernando.proyectoJDBC.jdbc.*;

public class EmployeesDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return EmployeesDao
	 */
	public static EmployeesDao create()
	{
		return new EmployeesDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return EmployeesDao
	 */
	public static EmployeesDao create(Connection conn)
	{
		return new EmployeesDaoImpl( conn );
	}

}
